# Generated by Django 5.1.4 on 2024-12-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_location_address'),
        ('recommendation', '0002_location_image'),
    ]

    operations = [
    ]
