# Generated by Django 5.1.1 on 2024-12-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_location_address'),
        ('recommendation', '0002_location_image'),
    ]

    operations = [
    ]
