# Generated by Django 5.1.3 on 2024-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
