# Generated by Django 5.1.1 on 2024-12-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_location_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='weather',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
