# Generated by Django 4.2.16 on 2024-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_eventreminder_latitude_eventreminder_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminder',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
