# Generated by Django 5.1.4 on 2024-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0003_alter_eventreminder_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reminder_images/'),
        ),
    ]
