# Generated by Django 5.1.1 on 2024-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0004_eventreminder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
