# Generated by Django 5.1.1 on 2024-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0013_remove_eventreminder_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
