# Generated by Django 5.1.1 on 2024-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0014_eventreminder_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreminder',
            name='event_reminder_id',
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
