# Generated by Django 4.2.16 on 2024-11-21 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
