# Generated by Django 4.2.16 on 2024-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_eventreminder_date_alter_eventreminder_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminder',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
